# DO NOT EDIT: generated by `make codegen` from schema/*.schema.json
# via datamodel-code-generator. Edit the schema, then regenerate.

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field


class Outcome(StrEnum):
    """
    Terminal state of this worker turn, interpreted by the dispatcher's state machine.
    """

    done = 'done'
    needs_review = 'needs_review'
    changes_requested = 'changes_requested'
    blocked = 'blocked'
    continue_ = 'continue'


class Tokens(BaseModel):
    """
    Token usage for this turn.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    in_: int = Field(..., alias='in')
    out: int


class Lane(StrEnum):
    """
    The DAC profile a worker runs under for an issue.
    """

    coder = 'coder'
    reviewer = 'reviewer'
    git_operator = 'git_operator'
    scribe = 'scribe'


class Column(StrEnum):
    """
    Board column (kanban state) an issue occupies.
    """

    todo = 'todo'
    ready = 'ready'
    running = 'running'
    review = 'review'
    merging = 'merging'
    documentation = 'documentation'
    done = 'done'
    rework = 'rework'
    blocked = 'blocked'


class BlockKind(StrEnum):
    """
    The reason a run is blocked; present on a worker result iff outcome=="blocked".
    """

    needs_input = 'needs_input'
    capability = 'capability'
    transient = 'transient'


class WorkerResult(BaseModel):
    """
    Typed result a clipse-worker subprocess writes to stdout after each turn. The dispatcher is the only consumer; it drives every board transition off this contract. See board.schema.json for the canonical Lane/BlockKind enums this schema references.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    run_id: str = Field(
        ..., description='Dispatcher-assigned identifier for this run/attempt.'
    )
    issue_id: str = Field(
        ..., description='Linear issue identifier this run is working.'
    )
    lane: Lane
    outcome: Outcome = Field(
        ...,
        description="Terminal state of this worker turn, interpreted by the dispatcher's state machine.",
    )
    block_kind: BlockKind | None = Field(
        None, description='Present iff outcome == "blocked"; omitted otherwise.'
    )
    summary: str = Field(
        ..., description='Human-readable summary of what happened this turn.'
    )
    artifacts: list[str] = Field(
        ...,
        description='Paths or references produced this turn (files touched, logs, etc).',
    )
    pr_url: str | None = Field(
        None, description='URL of the PR opened/updated this turn, if any. Optional.'
    )
    thread_id: str = Field(
        ...,
        description='LangGraph checkpointer thread id, for resuming continuation turns.',
    )
    turn_count: int = Field(
        ...,
        description='Number of turns run so far for this issue, including this one.',
    )
    tokens: Tokens = Field(..., description='Token usage for this turn.')
