VERSION ?= 0.1.0-dev
LDFLAGS  = -X github.com/xlyk/clipse/cli.Version=$(VERSION)
BINARY   = ./bin/clipse

# pinned codegen tool versions (bump deliberately; re-run `make codegen` after)
GO_JSONSCHEMA_VERSION      = v0.23.1
DATAMODEL_CODEGEN_VERSION  = 0.66.3

.PHONY: build test test-go test-py lint run codegen eval

## build: compile the clipse binary into ./bin/clipse
build:
	go build -ldflags "$(LDFLAGS)" -o $(BINARY) ./cmd/clipse

## test: run all tests (Go + Python)
test: test-go test-py

## test-go: run Go tests
test-go:
	go test ./...

## test-py: run Python tests (agent package)
test-py:
	cd agent && uv run pytest

## lint: vet and format check (Go) + ruff (Python)
lint:
	go vet ./...
	@unformatted=$$(gofmt -l .); \
	if [ -n "$$unformatted" ]; then \
	  echo "gofmt: the following files need formatting:"; \
	  echo "$$unformatted"; \
	  exit 1; \
	fi
	cd agent && uvx ruff check .

## codegen: regenerate Go + Python types from schema/. Must be idempotent.
codegen:
	go run github.com/atombender/go-jsonschema@$(GO_JSONSCHEMA_VERSION) \
		-p contract -t \
		schema/board.schema.json schema/worker-result.schema.json \
		-o internal/contract/contract.go
	gofmt -w internal/contract/contract.go
	uvx --from datamodel-code-generator==$(DATAMODEL_CODEGEN_VERSION) datamodel-codegen \
		--input schema/worker-result.schema.json \
		--input-file-type jsonschema \
		--output agent/src/clipse_agent/contract.py \
		--output-model-type pydantic_v2.BaseModel \
		--target-python-version 3.13 \
		--disable-timestamp \
		--use-schema-description \
		--field-constraints \
		--use-standard-collections \
		--use-union-operator
	@awk 'seen { print } /^$$/ { seen = 1 }' agent/src/clipse_agent/contract.py > agent/src/clipse_agent/contract.py.stripped
	@mv agent/src/clipse_agent/contract.py.stripped agent/src/clipse_agent/contract.py
	@{ \
	  echo "# DO NOT EDIT: generated by \`make codegen\` from schema/*.schema.json"; \
	  echo "# via datamodel-code-generator. Edit the schema, then regenerate."; \
	  echo; \
	  cat agent/src/clipse_agent/contract.py; \
	} > agent/src/clipse_agent/contract.py.tmp
	@mv agent/src/clipse_agent/contract.py.tmp agent/src/clipse_agent/contract.py

## run: run clipse via go run (no build step needed)
run:
	go run ./cmd/clipse

## eval: run live-model agent evals (needs ANTHROPIC_API_KEY; costs tokens)
eval:
	cd agent && uv run pytest evals -v
