// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contract

import "encoding/json"
import "fmt"
import "reflect"

type BlockKind string

const BlockKindCapability BlockKind = "capability"
const BlockKindNeedsInput BlockKind = "needs_input"
const BlockKindTransient BlockKind = "transient"

var enumValues_BlockKind = []interface{}{
	"needs_input",
	"capability",
	"transient",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *BlockKind) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_BlockKind {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_BlockKind, v)
	}
	*j = BlockKind(v)
	return nil
}

type Column string

const ColumnBlocked Column = "blocked"
const ColumnDone Column = "done"
const ColumnMerging Column = "merging"
const ColumnReady Column = "ready"
const ColumnReview Column = "review"
const ColumnRework Column = "rework"
const ColumnRunning Column = "running"
const ColumnTodo Column = "todo"

var enumValues_Column = []interface{}{
	"todo",
	"ready",
	"running",
	"review",
	"merging",
	"done",
	"rework",
	"blocked",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Column) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_Column {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_Column, v)
	}
	*j = Column(v)
	return nil
}

type Lane string

const LaneCoder Lane = "coder"
const LaneGitOperator Lane = "git_operator"
const LaneReviewer Lane = "reviewer"

var enumValues_Lane = []interface{}{
	"coder",
	"reviewer",
	"git_operator",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Lane) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_Lane {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_Lane, v)
	}
	*j = Lane(v)
	return nil
}

// Typed result a clipse-worker subprocess writes to stdout after each turn. The
// dispatcher is the only consumer; it drives every board transition off this
// contract. See board.schema.json for the canonical Lane/BlockKind enums this
// schema references.
type WorkerResult struct {
	// Paths or references produced this turn (files touched, logs, etc).
	Artifacts []string `json:"artifacts" yaml:"artifacts" mapstructure:"artifacts"`

	// Present iff outcome == "blocked"; omitted otherwise.
	BlockKind *BlockKind `json:"block_kind,omitempty,omitzero" yaml:"block_kind,omitempty" mapstructure:"block_kind,omitempty"`

	// Structured handoff note for the issue's Linear thread: decisions, interfaces,
	// deviations, gotchas for dependents. Optional; present only when the lane
	// produced one.
	Handoff *string `json:"handoff,omitempty,omitzero" yaml:"handoff,omitempty" mapstructure:"handoff,omitempty"`

	// Linear issue identifier this run is working.
	IssueId string `json:"issue_id" yaml:"issue_id" mapstructure:"issue_id"`

	// Lane corresponds to the JSON schema field "lane".
	Lane Lane `json:"lane" yaml:"lane" mapstructure:"lane"`

	// Terminal state of this worker turn, interpreted by the dispatcher's state
	// machine.
	Outcome WorkerResultOutcome `json:"outcome" yaml:"outcome" mapstructure:"outcome"`

	// URL of the PR opened/updated this turn, if any. Optional.
	PrUrl *string `json:"pr_url,omitempty,omitzero" yaml:"pr_url,omitempty" mapstructure:"pr_url,omitempty"`

	// Dispatcher-assigned identifier for this run/attempt.
	RunId string `json:"run_id" yaml:"run_id" mapstructure:"run_id"`

	// Human-readable summary of what happened this turn.
	Summary string `json:"summary" yaml:"summary" mapstructure:"summary"`

	// LangGraph checkpointer thread id, for resuming continuation turns.
	ThreadId string `json:"thread_id" yaml:"thread_id" mapstructure:"thread_id"`

	// Token usage for this turn.
	Tokens WorkerResultTokens `json:"tokens" yaml:"tokens" mapstructure:"tokens"`

	// Number of turns run so far for this issue, including this one.
	TurnCount int `json:"turn_count" yaml:"turn_count" mapstructure:"turn_count"`
}

type WorkerResultOutcome string

const WorkerResultOutcomeBlocked WorkerResultOutcome = "blocked"
const WorkerResultOutcomeChangesRequested WorkerResultOutcome = "changes_requested"
const WorkerResultOutcomeContinue WorkerResultOutcome = "continue"
const WorkerResultOutcomeDone WorkerResultOutcome = "done"
const WorkerResultOutcomeNeedsReview WorkerResultOutcome = "needs_review"

var enumValues_WorkerResultOutcome = []interface{}{
	"done",
	"needs_review",
	"changes_requested",
	"blocked",
	"continue",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *WorkerResultOutcome) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_WorkerResultOutcome {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_WorkerResultOutcome, v)
	}
	*j = WorkerResultOutcome(v)
	return nil
}

// Token usage for this turn.
type WorkerResultTokens struct {
	// In corresponds to the JSON schema field "in".
	In int `json:"in" yaml:"in" mapstructure:"in"`

	// Out corresponds to the JSON schema field "out".
	Out int `json:"out" yaml:"out" mapstructure:"out"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *WorkerResultTokens) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["in"]; raw != nil && !ok {
		return fmt.Errorf("field in in WorkerResultTokens: required")
	}
	if _, ok := raw["out"]; raw != nil && !ok {
		return fmt.Errorf("field out in WorkerResultTokens: required")
	}
	type Plain WorkerResultTokens
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = WorkerResultTokens(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *WorkerResult) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["artifacts"]; raw != nil && !ok {
		return fmt.Errorf("field artifacts in WorkerResult: required")
	}
	if _, ok := raw["issue_id"]; raw != nil && !ok {
		return fmt.Errorf("field issue_id in WorkerResult: required")
	}
	if _, ok := raw["lane"]; raw != nil && !ok {
		return fmt.Errorf("field lane in WorkerResult: required")
	}
	if _, ok := raw["outcome"]; raw != nil && !ok {
		return fmt.Errorf("field outcome in WorkerResult: required")
	}
	if _, ok := raw["run_id"]; raw != nil && !ok {
		return fmt.Errorf("field run_id in WorkerResult: required")
	}
	if _, ok := raw["summary"]; raw != nil && !ok {
		return fmt.Errorf("field summary in WorkerResult: required")
	}
	if _, ok := raw["thread_id"]; raw != nil && !ok {
		return fmt.Errorf("field thread_id in WorkerResult: required")
	}
	if _, ok := raw["tokens"]; raw != nil && !ok {
		return fmt.Errorf("field tokens in WorkerResult: required")
	}
	if _, ok := raw["turn_count"]; raw != nil && !ok {
		return fmt.Errorf("field turn_count in WorkerResult: required")
	}
	type Plain WorkerResult
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = WorkerResult(plain)
	return nil
}
