package setup

import (
	"fmt"

	"gopkg.in/yaml.v3"

	"github.com/xlyk/clipse/internal/config"
)

const documentHeader = "# Generated by `clipse configure`. Secret values stay outside this file.\n"

type configDocument struct {
	Repo             config.Repo               `yaml:"repo"`
	TeamKey          string                    `yaml:"team_key"`
	TeamID           string                    `yaml:"team_id"`
	LaneLabelPrefix  string                    `yaml:"lane_label_prefix"`
	StateLabelPrefix string                    `yaml:"state_label_prefix,omitempty"`
	AgentBackend     agentBackendDocument      `yaml:"agent_backend"`
	Worker           config.Worker             `yaml:"worker"`
	Models           config.Models             `yaml:"models"`
	ModelParams      map[string]map[string]any `yaml:"model_params,omitempty"`
	ShellAllowList   map[string]any            `yaml:"shell_allow_list"`
	EnvAllowlist     []string                  `yaml:"env_allowlist"`
	PollIntervalS    int                       `yaml:"poll_interval_s"`
	Caps             config.Caps               `yaml:"caps"`
	TurnCap          int                       `yaml:"turn_cap"`
	MaxRuntimeS      int                       `yaml:"max_runtime_s"`
	MaxTokensPerRun  int                       `yaml:"max_tokens_per_run"`
	MaxAttempts      int                       `yaml:"max_attempts"`
	ReworkCap        int                       `yaml:"rework_cap"`
	RecoverCap       int                       `yaml:"recover_cap"`
	RecoverBackoffS  int                       `yaml:"recover_backoff_s"`
	BoardDir         string                    `yaml:"board_dir"`
	CheckpointsDir   string                    `yaml:"checkpoints_dir"`
}

type agentBackendDocument struct {
	Type    string                 `yaml:"type"`
	Daytona daytonaBackendDocument `yaml:"daytona"`
}

type daytonaBackendDocument struct {
	AutoStopMinutes           int    `yaml:"auto_stop_minutes"`
	ReviewerAutoDeleteMinutes int    `yaml:"reviewer_auto_delete_minutes"`
	Snapshot                  string `yaml:"snapshot,omitempty"`
	Target                    string `yaml:"target,omitempty"`
}

// Render returns a stable, explicit clipse YAML document and validates those
// exact bytes through the same parser used by dispatch.
func Render(cfg config.Config) ([]byte, error) {
	params := make(map[string]map[string]any)
	if cfg.ModelParams.Coder != nil {
		params["coder"] = cfg.ModelParams.Coder
	}
	if cfg.ModelParams.CoderDocs != nil {
		params["coder_docs"] = cfg.ModelParams.CoderDocs
	}
	if cfg.ModelParams.Reviewer != nil {
		params["reviewer"] = cfg.ModelParams.Reviewer
	}
	if len(params) == 0 {
		params = nil
	}

	doc := configDocument{
		Repo:             cfg.Repo,
		TeamKey:          cfg.TeamKey,
		TeamID:           cfg.TeamID,
		LaneLabelPrefix:  cfg.LaneLabelPrefix,
		StateLabelPrefix: cfg.StateLabelPrefix,
		AgentBackend: agentBackendDocument{
			Type: cfg.AgentBackend.Type,
			Daytona: daytonaBackendDocument{
				AutoStopMinutes:           cfg.AgentBackend.Daytona.AutoStopMinutes,
				ReviewerAutoDeleteMinutes: cfg.AgentBackend.Daytona.ReviewerAutoDeleteMinutes,
				Snapshot:                  cfg.AgentBackend.Daytona.Snapshot,
				Target:                    cfg.AgentBackend.Daytona.Target,
			},
		},
		Worker:      cfg.Worker,
		Models:      cfg.Models,
		ModelParams: params,
		ShellAllowList: map[string]any{
			"coder":      shellValue(cfg.Shell.Coder),
			"coder_docs": shellValue(cfg.Shell.CoderDocs),
			"reviewer":   shellValue(cfg.Shell.Reviewer),
		},
		EnvAllowlist:    append([]string(nil), cfg.EnvAllowlist...),
		PollIntervalS:   cfg.PollIntervalS,
		Caps:            cfg.Caps,
		TurnCap:         cfg.TurnCap,
		MaxRuntimeS:     cfg.MaxRuntimeS,
		MaxTokensPerRun: cfg.MaxTokensPerRun,
		MaxAttempts:     cfg.MaxAttempts,
		ReworkCap:       cfg.ReworkCap,
		RecoverCap:      cfg.RecoverCap,
		RecoverBackoffS: cfg.RecoverBackoffS,
		BoardDir:        cfg.BoardDir,
		CheckpointsDir:  cfg.CheckpointsDir,
	}
	raw, err := yaml.Marshal(doc)
	if err != nil {
		return nil, fmt.Errorf("rendering config yaml: %w", err)
	}
	raw = append([]byte(documentHeader), raw...)
	if _, err := config.Parse(raw, "wizard draft"); err != nil {
		return nil, fmt.Errorf("validating rendered config: %w", err)
	}
	return raw, nil
}

func shellValue(policy config.ShellPolicy) any {
	if policy.All {
		return "all"
	}
	return append([]string(nil), policy.Commands...)
}
